/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.logging.Level;
import java.util.logging.Logger;

import java_cup.runtime.Symbol;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.TreeMap;


/**
 *
 * @author fabri
 */
// Guarda cada token que sale del lexer con su tipo, lexema, línea y columna
record Occ(String tipo, String lexema, int linea, int col) {}

public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane1.setViewportView(txtResultado);

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane2.setViewportView(txtEntrada);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        File archivo = new File("archivo.txt");
        PrintWriter escribir;
        try {
            escribir = new PrintWriter(archivo);
            escribir.print(txtEntrada.getText());
            escribir.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            Reader lector = new BufferedReader(new FileReader("archivo.txt"));
            Lexer lexer = new Lexer(lector);
            String resultado = "";
            while (true) {
                //while infinito, hasta que se analice el ultimo texto del txt
                Tokens tokens = lexer.yylex();
                if (tokens == null) {
                    resultado += "Termino";
                    txtResultado.setText(resultado);
                    return;
                }
                switch (tokens) {
                    case ERROR:
                        resultado += "Simbolo no definido\n";
                        break;
                    case IDENTIFICADOR: case ENTERO: case PALABRARESERVADA: case STRING: case CHAR: case OPERADORES: case REAL:
                        resultado += lexer.lexeme + " :Es un " + tokens + "\n";
                        break;
                    default:
                        resultado += "Token " + tokens + "\n";
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAnalizarActionPerformed
    */
    // ===== 1) Acción del botón: orquestación =====
    //coordina todo el flujo cuando se presiona Analizar.
    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        File archivo = new File("archivo.txt");
        try {
            guardarEntrada(archivo, txtEntrada.getText());

            // NUEVO: lista de ocurrencias token a token (tipo, lexema, línea, col)
            List<Occ> ocurrencias = new ArrayList<>();

            // Errores léxicos y sintácticos
            Map<Integer, java.util.List<String>> erroresPorLinea = new TreeMap<>();
            List<String> erroresSintacticos = new ArrayList<>();

            // Analiza y llena ocurrencias + errores
            analizarArchivo(archivo, ocurrencias, erroresPorLinea, erroresSintacticos);

            // Construye un resumen correcto por TIPO -> lexema -> posiciones
            String resumen = construirResumen(ocurrencias, erroresPorLinea, erroresSintacticos);
            txtResultado.setText(resumen);

        } catch (Exception ex) {
            txtResultado.setText("Error: " + ex.getMessage());
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // ===== 2) Guardar entrada (Responsabilidad: IO de entrada) =====
    private void guardarEntrada(File archivo, String contenido) throws FileNotFoundException {
        //Escribe exactamente lo que hay en txtEntrada a archivo.txt.
        try (PrintWriter escribir = new PrintWriter(archivo)) {
            escribir.print(contenido);
        }
    }
    
  // ===== 3) Analizar y acumular =====
    private void analizarArchivo(
            File archivo,
            List<Occ> ocurrencias,
            Map<Integer, java.util.List<String>> erroresPorLinea,
            List<String> erroresSintacticos
    ) throws IOException {

        // --- Análisis Léxico ---
        try (Reader lector = new BufferedReader(new FileReader(archivo))) {
            Lexer lexer = new Lexer(lector);
            Symbol token;

            while (true) {
                token = lexer.next_token();
                if (token.sym == sym.EOF) break;

                if (token.sym == sym.ERROR) {
                    String errorLexema = String.valueOf(token.value);
                    erroresPorLinea
                        .computeIfAbsent(token.left, k -> new ArrayList<>())
                        .add(errorLexema);
                    continue;
                }

                // Guarda cada ocurrencia con su TIPO, lexema, línea y columna
                String tipo   = sym.terminalNames[token.sym];
                String lexema = String.valueOf(token.value);
                ocurrencias.add(new Occ(tipo, lexema, token.left, token.right));
            }
        }

        // --- Análisis Sintáctico ---
        try (Reader lector2 = new BufferedReader(new FileReader(archivo))) {
            Lexer lexer2 = new Lexer(lector2);
            Parser parser = new Parser(lexer2);

            try {
                parser.parse();
            } catch (Exception e) {
                erroresSintacticos.add("Error durante parsing: " + e.getMessage());
            }

            java.util.List<String> erroresParser = parser.getErroresSintacticos();
            if (erroresParser != null && !erroresParser.isEmpty()) {
                erroresSintacticos.addAll(erroresParser);
            }

        } catch (Exception e) {
            erroresSintacticos.add("Error en análisis sintáctico: " + e.getMessage());
        }
    }

    // ===== 4) Construir salida =====
    private String construirResumen(
            List<Occ> ocurrencias,
            Map<Integer, java.util.List<String>> erroresPorLinea,
            List<String> erroresSintacticos
    ) {
        StringBuilder out = new StringBuilder();

        out.append("=== Resumen de Tokens (sin errores) ===\n");
        out.append(String.format("%-24s  %-20s  %s\n",
                "TOKEN (lexema)", "TIPO", "OCURRENCIAS POR LINEA"));
        out.append("-------------------------------------------------------------------------------\n");

    // Indice: agrupado por TIPO -> lexema -> lista de posiciones "l.x:y"
        Map<String, Map<String, List<String>>> idx = new TreeMap<>();

        for (Occ o : ocurrencias) {
            idx.computeIfAbsent(o.tipo(), k -> new TreeMap<>())
            .computeIfAbsent(o.lexema(), k -> new ArrayList<>())
            .add("l. " + o.linea() + ":" + o.col());
        }

        for (var eTipo : idx.entrySet()) {
            String tipo = eTipo.getKey();
            for (var eLex : eTipo.getValue().entrySet()) {
                String lexema = eLex.getKey();
                String pos = String.join(", ", eLex.getValue());
                out.append(String.format("%-24s  %-20s  %s\n", lexema, tipo, pos));
            }
        }

        // ---- Errores léxicos ----
        out.append("\n=== Errores léxicos ===\n");
        if (erroresPorLinea.isEmpty()) {
            out.append("No se encontraron errores léxicos.\n");
        } else {
            for (Map.Entry<Integer, java.util.List<String>> entry : erroresPorLinea.entrySet()) {
                int line = entry.getKey();
                String unidos = String.join(" | ", entry.getValue());
                out.append("l. ").append(line).append(": ").append(unidos).append("\n");
            }
        }

        // ---- Errores sintácticos ----
        out.append("\n=== Errores sintácticos ===\n");
        if (erroresSintacticos.isEmpty()) {
            out.append("No se encontraron errores sintácticos.\n");
        } else {
            for (String error : erroresSintacticos) {
                out.append(error).append("\n");
            }
        }

        return out.toString();
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}