
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

import java_cup.runtime.Symbol;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\151\000\002\002\004\000\002\002\007\000\002\002" +
    "\007\000\002\002\003\000\002\040\002\000\002\003\005" +
    "\000\002\003\004\000\002\003\002\000\002\004\004\000" +
    "\002\004\003\000\002\005\006\000\002\005\010\000\002" +
    "\005\004\000\002\005\006\000\002\005\010\000\002\006" +
    "\003\000\002\006\005\000\002\007\003\000\002\007\003" +
    "\000\002\007\003\000\002\007\003\000\002\010\003\000" +
    "\002\010\002\000\002\011\004\000\002\011\003\000\002" +
    "\012\012\000\002\012\012\000\002\012\010\000\002\012" +
    "\010\000\002\013\003\000\002\013\002\000\002\014\005" +
    "\000\002\014\003\000\002\015\004\000\002\015\004\000" +
    "\002\016\006\000\002\016\006\000\002\037\004\000\002" +
    "\037\002\000\002\017\005\000\002\017\005\000\002\020" +
    "\005\000\002\021\004\000\002\021\002\000\002\021\004" +
    "\000\002\022\004\000\002\022\004\000\002\022\004\000" +
    "\002\022\004\000\002\022\003\000\002\022\003\000\002" +
    "\022\003\000\002\023\005\000\002\023\005\000\002\024" +
    "\006\000\002\024\006\000\002\025\005\000\002\025\006" +
    "\000\002\025\006\000\002\026\006\000\002\026\006\000" +
    "\002\032\003\000\002\032\002\000\002\033\005\000\002" +
    "\033\003\000\002\030\006\000\002\030\006\000\002\031" +
    "\012\000\002\031\012\000\002\031\012\000\002\031\012" +
    "\000\002\027\006\000\002\027\010\000\002\027\006\000" +
    "\002\027\006\000\002\027\010\000\002\035\003\000\002" +
    "\034\005\000\002\034\005\000\002\034\005\000\002\034" +
    "\005\000\002\034\005\000\002\034\005\000\002\034\004" +
    "\000\002\034\004\000\002\034\004\000\002\034\004\000" +
    "\002\034\005\000\002\034\005\000\002\034\005\000\002" +
    "\034\005\000\002\034\005\000\002\034\005\000\002\034" +
    "\005\000\002\034\005\000\002\034\004\000\002\034\003" +
    "\000\002\036\003\000\002\036\003\000\002\036\003\000" +
    "\002\036\003\000\002\036\003\000\002\036\006\000\002" +
    "\036\005\000\002\036\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\327\000\006\003\005\047\006\001\002\000\004\002" +
    "\331\001\002\000\004\002\ufffe\001\002\000\004\124\007" +
    "\001\002\000\014\003\ufffa\007\ufffa\025\ufffa\046\ufffa\063" +
    "\010\001\002\000\006\003\326\124\ufffd\001\002\000\012" +
    "\003\uffeb\007\uffeb\025\016\046\013\001\002\000\012\003" +
    "\uffec\007\uffec\025\016\046\013\001\002\000\004\124\315" +
    "\001\002\000\006\003\306\007\307\001\002\000\012\003" +
    "\uffe9\007\uffe9\025\uffe9\046\uffe9\001\002\000\004\124\017" +
    "\001\002\000\004\105\020\001\002\000\016\003\027\071" +
    "\021\072\026\073\031\074\024\106\uffe3\001\002\000\014" +
    "\003\ufff0\007\ufff0\063\ufff0\103\ufff0\124\ufff0\001\002\000" +
    "\004\106\302\001\002\000\006\104\300\106\uffe4\001\002" +
    "\000\014\003\uffed\007\uffed\063\uffed\103\uffed\124\uffed\001" +
    "\002\000\006\104\uffe1\106\uffe1\001\002\000\014\003\uffef" +
    "\007\uffef\063\uffef\103\uffef\124\uffef\001\002\000\004\106" +
    "\034\001\002\000\006\003\033\124\032\001\002\000\014" +
    "\003\uffee\007\uffee\063\uffee\103\uffee\124\uffee\001\002\000" +
    "\006\104\uffe0\106\uffe0\001\002\000\006\104\uffdf\106\uffdf" +
    "\001\002\000\004\121\035\001\002\000\012\071\021\072" +
    "\026\073\031\074\024\001\002\000\006\007\uffdb\063\037" +
    "\001\002\000\004\124\257\001\002\000\012\003\uffe7\007" +
    "\uffe7\025\uffe7\046\uffe7\001\002\000\004\007\042\001\002" +
    "\000\022\003\043\020\uffd6\023\uffd6\027\uffd6\065\uffd6\067" +
    "\uffd6\070\uffd6\124\uffd6\001\002\000\006\020\255\103\205" +
    "\001\002\000\020\020\062\023\050\027\057\065\046\067" +
    "\061\070\045\124\060\001\002\000\004\105\247\001\002" +
    "\000\026\003\241\040\076\076\074\077\066\100\065\101" +
    "\101\105\100\122\075\123\077\124\070\001\002\000\020" +
    "\020\uffd0\023\uffd0\027\uffd0\065\uffd0\067\uffd0\070\uffd0\124" +
    "\uffd0\001\002\000\004\124\214\001\002\000\004\103\213" +
    "\001\002\000\020\020\uffd7\023\uffd7\027\uffd7\065\uffd7\067" +
    "\uffd7\070\uffd7\124\uffd7\001\002\000\004\103\212\001\002" +
    "\000\004\103\211\001\002\000\004\103\210\001\002\000" +
    "\020\020\uffcf\023\uffcf\027\uffcf\065\uffcf\067\uffcf\070\uffcf" +
    "\124\uffcf\001\002\000\026\003\171\040\076\076\074\077" +
    "\066\100\065\101\101\105\100\122\075\123\077\124\070" +
    "\001\002\000\010\003\157\102\161\105\160\001\002\000" +
    "\004\105\064\001\002\000\012\003\uffde\007\uffde\025\uffde" +
    "\046\uffde\001\002\000\020\020\uffce\023\uffce\027\uffce\065" +
    "\uffce\067\uffce\070\uffce\124\uffce\001\002\000\026\003\072" +
    "\040\076\076\074\077\066\100\065\101\101\105\100\122" +
    "\075\123\077\124\070\001\002\000\056\005\uff9e\014\uff9e" +
    "\015\uff9e\036\uff9e\043\uff9e\055\uff9e\056\uff9e\103\uff9e\104" +
    "\uff9e\106\uff9e\107\uff9e\110\uff9e\111\uff9e\112\uff9e\113\uff9e" +
    "\114\uff9e\115\uff9e\116\uff9e\117\uff9e\120\uff9e\122\uff9e\123" +
    "\uff9e\001\002\000\056\005\uff9c\014\uff9c\015\uff9c\036\uff9c" +
    "\043\uff9c\055\uff9c\056\uff9c\103\uff9c\104\uff9c\106\uff9c\107" +
    "\uff9c\110\uff9c\111\uff9c\112\uff9c\113\uff9c\114\uff9c\115\uff9c" +
    "\116\uff9c\117\uff9c\120\uff9c\122\uff9c\123\uff9c\001\002\000" +
    "\046\005\106\014\116\036\111\043\125\104\uffc1\106\uffc1" +
    "\107\113\110\112\111\115\112\110\113\124\114\117\115" +
    "\114\116\105\117\121\120\107\122\122\123\123\001\002" +
    "\000\060\005\uffa0\014\uffa0\015\uffa0\036\uffa0\043\uffa0\055" +
    "\uffa0\056\uffa0\103\uffa0\104\uffa0\105\153\106\uffa0\107\uffa0" +
    "\110\uffa0\111\uffa0\112\uffa0\113\uffa0\114\uffa0\115\uffa0\116" +
    "\uffa0\117\uffa0\120\uffa0\122\uffa0\123\uffa0\001\002\000\056" +
    "\005\uffa1\014\uffa1\015\uffa1\036\uffa1\043\uffa1\055\uffa1\056" +
    "\uffa1\103\uffa1\104\uffa1\106\uffa1\107\uffa1\110\uffa1\111\uffa1" +
    "\112\uffa1\113\uffa1\114\uffa1\115\uffa1\116\uffa1\117\uffa1\120" +
    "\uffa1\122\uffa1\123\uffa1\001\002\000\004\106\152\001\002" +
    "\000\006\104\147\106\150\001\002\000\056\005\uff9d\014" +
    "\uff9d\015\uff9d\036\uff9d\043\uff9d\055\uff9d\056\uff9d\103\uff9d" +
    "\104\uff9d\106\uff9d\107\uff9d\110\uff9d\111\uff9d\112\uff9d\113" +
    "\uff9d\114\uff9d\115\uff9d\116\uff9d\117\uff9d\120\uff9d\122\uff9d" +
    "\123\uff9d\001\002\000\024\040\076\076\074\077\066\100" +
    "\065\101\101\105\100\122\075\123\077\124\070\001\002" +
    "\000\024\040\076\076\074\077\066\100\065\101\101\105" +
    "\100\122\075\123\077\124\070\001\002\000\024\040\076" +
    "\076\074\077\066\100\065\101\101\105\100\122\075\123" +
    "\077\124\070\001\002\000\026\003\103\040\076\076\074" +
    "\077\066\100\065\101\101\105\100\122\075\123\077\124" +
    "\070\001\002\000\056\005\uff9f\014\uff9f\015\uff9f\036\uff9f" +
    "\043\uff9f\055\uff9f\056\uff9f\103\uff9f\104\uff9f\106\uff9f\107" +
    "\uff9f\110\uff9f\111\uff9f\112\uff9f\113\uff9f\114\uff9f\115\uff9f" +
    "\116\uff9f\117\uff9f\120\uff9f\122\uff9f\123\uff9f\001\002\000" +
    "\044\005\106\014\116\036\111\043\125\106\120\107\113" +
    "\110\112\111\115\112\110\113\124\114\117\115\114\116" +
    "\105\117\121\120\107\122\122\123\123\001\002\000\004" +
    "\106\104\001\002\000\056\005\uff99\014\uff99\015\uff99\036" +
    "\uff99\043\uff99\055\uff99\056\uff99\103\uff99\104\uff99\106\uff99" +
    "\107\uff99\110\uff99\111\uff99\112\uff99\113\uff99\114\uff99\115" +
    "\uff99\116\uff99\117\uff99\120\uff99\122\uff99\123\uff99\001\002" +
    "\000\024\040\076\076\074\077\066\100\065\101\101\105" +
    "\100\122\075\123\077\124\070\001\002\000\024\040\076" +
    "\076\074\077\066\100\065\101\101\105\100\122\075\123" +
    "\077\124\070\001\002\000\024\040\076\076\074\077\066" +
    "\100\065\101\101\105\100\122\075\123\077\124\070\001" +
    "\002\000\024\040\076\076\074\077\066\100\065\101\101" +
    "\105\100\122\075\123\077\124\070\001\002\000\024\040" +
    "\076\076\074\077\066\100\065\101\101\105\100\122\075" +
    "\123\077\124\070\001\002\000\024\040\076\076\074\077" +
    "\066\100\065\101\101\105\100\122\075\123\077\124\070" +
    "\001\002\000\024\040\076\076\074\077\066\100\065\101" +
    "\101\105\100\122\075\123\077\124\070\001\002\000\024" +
    "\040\076\076\074\077\066\100\065\101\101\105\100\122" +
    "\075\123\077\124\070\001\002\000\024\040\076\076\074" +
    "\077\066\100\065\101\101\105\100\122\075\123\077\124" +
    "\070\001\002\000\024\040\076\076\074\077\066\100\065" +
    "\101\101\105\100\122\075\123\077\124\070\001\002\000" +
    "\024\040\076\076\074\077\066\100\065\101\101\105\100" +
    "\122\075\123\077\124\070\001\002\000\056\005\uff9a\014" +
    "\uff9a\015\uff9a\036\uff9a\043\uff9a\055\uff9a\056\uff9a\103\uff9a" +
    "\104\uff9a\106\uff9a\107\uff9a\110\uff9a\111\uff9a\112\uff9a\113" +
    "\uff9a\114\uff9a\115\uff9a\116\uff9a\117\uff9a\120\uff9a\122\uff9a" +
    "\123\uff9a\001\002\000\024\040\076\076\074\077\066\100" +
    "\065\101\101\105\100\122\075\123\077\124\070\001\002" +
    "\000\056\005\uffae\014\uffae\015\uffae\036\uffae\043\uffae\055" +
    "\uffae\056\uffae\103\uffae\104\uffae\106\uffae\107\uffae\110\uffae" +
    "\111\uffae\112\uffae\113\uffae\114\uffae\115\uffae\116\uffae\117" +
    "\uffae\120\uffae\122\uffae\123\uffae\001\002\000\056\005\uffad" +
    "\014\uffad\015\uffad\036\uffad\043\uffad\055\uffad\056\uffad\103" +
    "\uffad\104\uffad\106\uffad\107\uffad\110\uffad\111\uffad\112\uffad" +
    "\113\uffad\114\uffad\115\uffad\116\uffad\117\uffad\120\uffad\122" +
    "\uffad\123\uffad\001\002\000\024\040\076\076\074\077\066" +
    "\100\065\101\101\105\100\122\075\123\077\124\070\001" +
    "\002\000\024\040\076\076\074\077\066\100\065\101\101" +
    "\105\100\122\075\123\077\124\070\001\002\000\056\005" +
    "\uffa3\014\116\015\uffa3\036\111\043\uffa3\055\uffa3\056\uffa3" +
    "\103\uffa3\104\uffa3\106\uffa3\107\113\110\112\111\115\112" +
    "\110\113\124\114\117\115\114\116\105\117\121\120\107" +
    "\122\122\123\123\001\002\000\042\005\uffa8\014\116\015" +
    "\uffa8\036\111\043\uffa8\055\uffa8\056\uffa8\103\uffa8\104\uffa8" +
    "\106\uffa8\115\114\116\105\117\121\120\107\122\122\123" +
    "\123\001\002\000\056\005\uffb2\014\uffb2\015\uffb2\036\uffb2" +
    "\043\uffb2\055\uffb2\056\uffb2\103\uffb2\104\uffb2\106\uffb2\107" +
    "\uffb2\110\uffb2\111\uffb2\112\uffb2\113\uffb2\114\uffb2\115\uffb2" +
    "\116\uffb2\117\uffb2\120\uffb2\122\uffb2\123\uffb2\001\002\000" +
    "\042\005\uffa6\014\116\015\uffa6\036\111\043\uffa6\055\uffa6" +
    "\056\uffa6\103\uffa6\104\uffa6\106\uffa6\115\114\116\105\117" +
    "\121\120\107\122\122\123\123\001\002\000\056\005\uffb0" +
    "\014\uffb0\015\uffb0\036\uffb0\043\uffb0\055\uffb0\056\uffb0\103" +
    "\uffb0\104\uffb0\106\uffb0\107\uffb0\110\uffb0\111\uffb0\112\uffb0" +
    "\113\uffb0\114\uffb0\115\uffb0\116\uffb0\117\uffb0\120\uffb0\122" +
    "\uffb0\123\uffb0\001\002\000\042\005\uffa7\014\116\015\uffa7" +
    "\036\111\043\uffa7\055\uffa7\056\uffa7\103\uffa7\104\uffa7\106" +
    "\uffa7\115\114\116\105\117\121\120\107\122\122\123\123" +
    "\001\002\000\056\005\uffb4\014\116\015\uffb4\036\111\043" +
    "\uffb4\055\uffb4\056\uffb4\103\uffb4\104\uffb4\106\uffb4\107\uffb4" +
    "\110\uffb4\111\uffb4\112\uffb4\113\uffb4\114\uffb4\115\uffb4\116" +
    "\uffb4\117\121\120\107\122\uffb4\123\uffb4\001\002\000\042" +
    "\005\uffaa\014\116\015\uffaa\036\111\043\uffaa\055\uffaa\056" +
    "\uffaa\103\uffaa\104\uffaa\106\uffaa\115\114\116\105\117\121" +
    "\120\107\122\122\123\123\001\002\000\042\005\uffa9\014" +
    "\116\015\uffa9\036\111\043\uffa9\055\uffa9\056\uffa9\103\uffa9" +
    "\104\uffa9\106\uffa9\115\114\116\105\117\121\120\107\122" +
    "\122\123\123\001\002\000\056\005\uffaf\014\uffaf\015\uffaf" +
    "\036\uffaf\043\uffaf\055\uffaf\056\uffaf\103\uffaf\104\uffaf\106" +
    "\uffaf\107\uffaf\110\uffaf\111\uffaf\112\uffaf\113\uffaf\114\uffaf" +
    "\115\uffaf\116\uffaf\117\uffaf\120\uffaf\122\uffaf\123\uffaf\001" +
    "\002\000\042\005\uffa5\014\116\015\uffa5\036\111\043\uffa5" +
    "\055\uffa5\056\uffa5\103\uffa5\104\uffa5\106\uffa5\115\114\116" +
    "\105\117\121\120\107\122\122\123\123\001\002\000\056" +
    "\005\uffb1\014\uffb1\015\uffb1\036\uffb1\043\uffb1\055\uffb1\056" +
    "\uffb1\103\uffb1\104\uffb1\106\uffb1\107\uffb1\110\uffb1\111\uffb1" +
    "\112\uffb1\113\uffb1\114\uffb1\115\uffb1\116\uffb1\117\uffb1\120" +
    "\uffb1\122\uffb1\123\uffb1\001\002\000\056\005\uffa4\014\116" +
    "\015\uffa4\036\111\043\uffa4\055\uffa4\056\uffa4\103\uffa4\104" +
    "\uffa4\106\uffa4\107\113\110\112\111\115\112\110\113\124" +
    "\114\117\115\114\116\105\117\121\120\107\122\122\123" +
    "\123\001\002\000\056\005\uffb3\014\116\015\uffb3\036\111" +
    "\043\uffb3\055\uffb3\056\uffb3\103\uffb3\104\uffb3\106\uffb3\107" +
    "\uffb3\110\uffb3\111\uffb3\112\uffb3\113\uffb3\114\uffb3\115\uffb3" +
    "\116\uffb3\117\121\120\107\122\uffb3\123\uffb3\001\002\000" +
    "\056\005\uffab\014\116\015\uffab\036\111\043\uffab\055\uffab" +
    "\056\uffab\103\uffab\104\uffab\106\uffab\107\uffab\110\uffab\111" +
    "\uffab\112\uffab\113\uffab\114\uffab\115\uffab\116\uffab\117\121" +
    "\120\107\122\uffab\123\uffab\001\002\000\056\005\uffa2\014" +
    "\116\015\uffa2\036\111\043\uffa2\055\uffa2\056\uffa2\103\uffa2" +
    "\104\uffa2\106\uffa2\107\113\110\112\111\115\112\110\113" +
    "\124\114\117\115\114\116\105\117\121\120\107\122\122" +
    "\123\123\001\002\000\056\005\uffac\014\116\015\uffac\036" +
    "\111\043\uffac\055\uffac\056\uffac\103\uffac\104\uffac\106\uffac" +
    "\107\uffac\110\uffac\111\uffac\112\uffac\113\uffac\114\uffac\115" +
    "\uffac\116\uffac\117\121\120\107\122\uffac\123\uffac\001\002" +
    "\000\024\040\076\076\074\077\066\100\065\101\101\105" +
    "\100\122\075\123\077\124\070\001\002\000\004\103\uffc6" +
    "\001\002\000\046\005\106\014\116\036\111\043\125\104" +
    "\uffc2\106\uffc2\107\113\110\112\111\115\112\110\113\124" +
    "\114\117\115\114\116\105\117\121\120\107\122\122\123" +
    "\123\001\002\000\004\103\uffc5\001\002\000\026\040\076" +
    "\076\074\077\066\100\065\101\101\105\100\106\uffc3\122" +
    "\075\123\077\124\070\001\002\000\006\104\147\106\uffc4" +
    "\001\002\000\004\106\156\001\002\000\056\005\uff9b\014" +
    "\uff9b\015\uff9b\036\uff9b\043\uff9b\055\uff9b\056\uff9b\103\uff9b" +
    "\104\uff9b\106\uff9b\107\uff9b\110\uff9b\111\uff9b\112\uff9b\113" +
    "\uff9b\114\uff9b\115\uff9b\116\uff9b\117\uff9b\120\uff9b\122\uff9b" +
    "\123\uff9b\001\002\000\024\040\076\076\074\077\066\100" +
    "\065\101\101\105\100\122\075\123\077\124\070\001\002" +
    "\000\030\003\163\040\076\076\074\077\066\100\065\101" +
    "\101\105\100\106\uffc3\122\075\123\077\124\070\001\002" +
    "\000\024\040\076\076\074\077\066\100\065\101\101\105" +
    "\100\122\075\123\077\124\070\001\002\000\044\005\106" +
    "\014\116\036\111\043\125\103\uffcd\107\113\110\112\111" +
    "\115\112\110\113\124\114\117\115\114\116\105\117\121" +
    "\120\107\122\122\123\123\001\002\000\004\106\166\001" +
    "\002\000\004\106\165\001\002\000\004\103\uffcb\001\002" +
    "\000\004\103\uffca\001\002\000\044\005\106\014\116\036" +
    "\111\043\125\103\uffcc\107\113\110\112\111\115\112\110" +
    "\113\124\114\117\115\114\116\105\117\121\120\107\122" +
    "\122\123\123\001\002\000\046\005\106\014\116\015\uffb5" +
    "\036\111\043\125\055\uffb5\107\113\110\112\111\115\112" +
    "\110\113\124\114\117\115\114\116\105\117\121\120\107" +
    "\122\122\123\123\001\002\000\004\055\206\001\002\000" +
    "\004\055\173\001\002\000\006\003\174\007\175\001\002" +
    "\000\020\020\uffb7\023\uffb7\027\uffb7\065\uffb7\067\uffb7\070" +
    "\uffb7\124\uffb7\001\002\000\022\003\202\020\uffd6\023\uffd6" +
    "\027\uffd6\065\uffd6\067\uffd6\070\uffd6\124\uffd6\001\002\000" +
    "\022\017\177\020\uffba\023\uffba\027\uffba\065\uffba\067\uffba" +
    "\070\uffba\124\uffba\001\002\000\006\003\200\007\175\001" +
    "\002\000\020\020\uffb6\023\uffb6\027\uffb6\065\uffb6\067\uffb6" +
    "\070\uffb6\124\uffb6\001\002\000\020\020\uffb9\023\uffb9\027" +
    "\uffb9\065\uffb9\067\uffb9\070\uffb9\124\uffb9\001\002\000\004" +
    "\103\205\001\002\000\020\020\204\023\050\027\057\065" +
    "\046\067\061\070\045\124\060\001\002\000\022\017\uffd8" +
    "\020\uffd8\023\uffd8\027\uffd8\065\uffd8\067\uffd8\070\uffd8\124" +
    "\uffd8\001\002\000\020\020\uffd5\023\uffd5\027\uffd5\065\uffd5" +
    "\067\uffd5\070\uffd5\124\uffd5\001\002\000\004\007\175\001" +
    "\002\000\020\020\uffb8\023\uffb8\027\uffb8\065\uffb8\067\uffb8" +
    "\070\uffb8\124\uffb8\001\002\000\020\020\uffd4\023\uffd4\027" +
    "\uffd4\065\uffd4\067\uffd4\070\uffd4\124\uffd4\001\002\000\020" +
    "\020\uffd2\023\uffd2\027\uffd2\065\uffd2\067\uffd2\070\uffd2\124" +
    "\uffd2\001\002\000\020\020\uffd3\023\uffd3\027\uffd3\065\uffd3" +
    "\067\uffd3\070\uffd3\124\uffd3\001\002\000\020\020\uffd1\023" +
    "\uffd1\027\uffd1\065\uffd1\067\uffd1\070\uffd1\124\uffd1\001\002" +
    "\000\006\003\215\102\216\001\002\000\024\040\076\076" +
    "\074\077\066\100\065\101\101\105\100\122\075\123\077" +
    "\124\070\001\002\000\026\003\220\040\076\076\074\077" +
    "\066\100\065\101\101\105\100\122\075\123\077\124\070" +
    "\001\002\000\044\005\106\014\116\036\111\043\125\056" +
    "\225\107\113\110\112\111\115\112\110\113\124\114\117" +
    "\115\114\116\105\117\121\120\107\122\122\123\123\001" +
    "\002\000\004\056\221\001\002\000\024\040\076\076\074" +
    "\077\066\100\065\101\101\105\100\122\075\123\077\124" +
    "\070\001\002\000\044\005\106\014\116\015\223\036\111" +
    "\043\125\107\113\110\112\111\115\112\110\113\124\114" +
    "\117\115\114\116\105\117\121\120\107\122\122\123\123" +
    "\001\002\000\004\007\175\001\002\000\020\020\uffbc\023" +
    "\uffbc\027\uffbc\065\uffbc\067\uffbc\070\uffbc\124\uffbc\001\002" +
    "\000\026\003\227\040\076\076\074\077\066\100\065\101" +
    "\101\105\100\122\075\123\077\124\070\001\002\000\044" +
    "\005\106\014\116\015\232\036\111\043\125\107\113\110" +
    "\112\111\115\112\110\113\124\114\117\115\114\116\105" +
    "\117\121\120\107\122\122\123\123\001\002\000\004\015" +
    "\230\001\002\000\004\007\175\001\002\000\020\020\uffbb" +
    "\023\uffbb\027\uffbb\065\uffbb\067\uffbb\070\uffbb\124\uffbb\001" +
    "\002\000\004\007\175\001\002\000\020\020\uffbe\023\uffbe" +
    "\027\uffbe\065\uffbe\067\uffbe\070\uffbe\124\uffbe\001\002\000" +
    "\044\005\106\014\116\036\111\043\125\056\235\107\113" +
    "\110\112\111\115\112\110\113\124\114\117\115\114\116" +
    "\105\117\121\120\107\122\122\123\123\001\002\000\024" +
    "\040\076\076\074\077\066\100\065\101\101\105\100\122" +
    "\075\123\077\124\070\001\002\000\044\005\106\014\116" +
    "\015\237\036\111\043\125\107\113\110\112\111\115\112" +
    "\110\113\124\114\117\115\114\116\105\117\121\120\107" +
    "\122\122\123\123\001\002\000\004\007\175\001\002\000" +
    "\020\020\uffbd\023\uffbd\027\uffbd\065\uffbd\067\uffbd\070\uffbd" +
    "\124\uffbd\001\002\000\004\015\245\001\002\000\004\015" +
    "\243\001\002\000\004\007\175\001\002\000\020\020\uffc0" +
    "\023\uffc0\027\uffc0\065\uffc0\067\uffc0\070\uffc0\124\uffc0\001" +
    "\002\000\004\007\175\001\002\000\020\020\uffbf\023\uffbf" +
    "\027\uffbf\065\uffbf\067\uffbf\070\uffbf\124\uffbf\001\002\000" +
    "\010\003\252\106\251\124\250\001\002\000\004\106\254" +
    "\001\002\000\004\103\uffc9\001\002\000\004\106\253\001" +
    "\002\000\004\103\uffc7\001\002\000\004\103\uffc8\001\002" +
    "\000\012\003\uffdd\007\uffdd\025\uffdd\046\uffdd\001\002\000" +
    "\014\003\ufff8\007\ufff8\025\ufff8\046\ufff8\124\ufff8\001\002" +
    "\000\010\003\263\104\262\121\264\001\002\000\006\007" +
    "\uffdc\124\257\001\002\000\014\003\ufff9\007\ufff9\025\ufff9" +
    "\046\ufff9\124\ufff9\001\002\000\004\124\270\001\002\000" +
    "\014\003\ufff5\007\ufff5\025\ufff5\046\ufff5\124\ufff5\001\002" +
    "\000\012\071\021\072\026\073\031\074\024\001\002\000" +
    "\006\003\266\103\267\001\002\000\014\003\ufff4\007\ufff4" +
    "\025\ufff4\046\ufff4\124\ufff4\001\002\000\014\003\ufff7\007" +
    "\ufff7\025\ufff7\046\ufff7\124\ufff7\001\002\000\006\104\ufff2" +
    "\121\ufff2\001\002\000\006\104\272\121\273\001\002\000" +
    "\004\124\277\001\002\000\012\071\021\072\026\073\031" +
    "\074\024\001\002\000\006\003\275\103\276\001\002\000" +
    "\014\003\ufff3\007\ufff3\025\ufff3\046\ufff3\124\ufff3\001\002" +
    "\000\014\003\ufff6\007\ufff6\025\ufff6\046\ufff6\124\ufff6\001" +
    "\002\000\006\104\ufff1\121\ufff1\001\002\000\012\071\021" +
    "\072\026\073\031\074\024\001\002\000\006\104\uffe2\106" +
    "\uffe2\001\002\000\004\121\303\001\002\000\012\071\021" +
    "\072\026\073\031\074\024\001\002\000\006\007\uffdb\063" +
    "\037\001\002\000\012\003\uffe8\007\uffe8\025\uffe8\046\uffe8" +
    "\001\002\000\004\002\uffff\001\002\000\022\003\311\020" +
    "\uffd6\023\uffd6\027\uffd6\065\uffd6\067\uffd6\070\uffd6\124\uffd6" +
    "\001\002\000\004\002\000\001\002\000\006\020\314\103" +
    "\205\001\002\000\020\020\313\023\050\027\057\065\046" +
    "\067\061\070\045\124\060\001\002\000\004\002\uffda\001" +
    "\002\000\004\002\uffd9\001\002\000\004\105\316\001\002" +
    "\000\016\003\320\071\021\072\026\073\031\074\024\106" +
    "\uffe3\001\002\000\004\106\323\001\002\000\004\106\321" +
    "\001\002\000\006\007\uffdb\063\037\001\002\000\012\003" +
    "\uffe5\007\uffe5\025\uffe5\046\uffe5\001\002\000\006\007\uffdb" +
    "\063\037\001\002\000\012\003\uffe6\007\uffe6\025\uffe6\046" +
    "\uffe6\001\002\000\012\003\uffea\007\uffea\025\uffea\046\uffea" +
    "\001\002\000\012\003\ufffb\007\ufffb\025\ufffb\046\ufffb\001" +
    "\002\000\004\124\257\001\002\000\014\003\ufffc\007\ufffc" +
    "\025\ufffc\046\ufffc\124\257\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\327\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\010\001\001" +
    "\000\004\040\326\001\001\000\010\010\013\011\011\012" +
    "\014\001\001\000\004\012\324\001\001\000\002\001\001" +
    "\000\004\017\307\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\007\027\013\021\014\022" +
    "\015\024\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\007\035\001\001\000\006\016\037\037\040\001" +
    "\001\000\006\004\257\005\255\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\021\043\001\001\000\002\001" +
    "\001\000\022\022\051\023\054\024\052\025\053\026\050" +
    "\027\046\030\055\031\062\001\001\000\002\001\001\000" +
    "\010\034\167\035\241\036\070\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\034\167\035\171\036\070\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\033\072\034\066\036\070\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\034\145\036\070\001\001" +
    "\000\006\034\144\036\070\001\001\000\006\034\143\036" +
    "\070\001\001\000\006\034\101\036\070\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\034\142\036\070\001\001\000\006\034\141" +
    "\036\070\001\001\000\006\034\140\036\070\001\001\000" +
    "\006\034\137\036\070\001\001\000\006\034\136\036\070" +
    "\001\001\000\006\034\135\036\070\001\001\000\006\034" +
    "\134\036\070\001\001\000\006\034\133\036\070\001\001" +
    "\000\006\034\132\036\070\001\001\000\006\034\131\036" +
    "\070\001\001\000\006\034\130\036\070\001\001\000\002" +
    "\001\001\000\006\034\127\036\070\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\034\126\036\070\001\001" +
    "\000\006\034\125\036\070\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\034\150\036\070\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\032\154\033\153\034\066" +
    "\036\070\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\034\166\036\070\001\001\000\012" +
    "\032\163\033\153\034\066\036\070\001\001\000\006\034" +
    "\161\036\070\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\020\175\001\001\000\002\001\001\000" +
    "\004\021\202\001\001\000\002\001\001\000\004\020\200" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\022\051\023\054\024\052\025\053\026\050" +
    "\027\046\030\055\031\062\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\020\206\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\034\233\036\070" +
    "\001\001\000\006\034\216\036\070\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\034\221\036\070\001\001" +
    "\000\002\001\001\000\004\020\223\001\001\000\002\001" +
    "\001\000\006\034\225\036\070\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\020\230\001\001\000\002\001" +
    "\001\000\004\020\232\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\034\235\036\070\001\001\000\002\001" +
    "\001\000\004\020\237\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\020\243\001\001\000" +
    "\002\001\001\000\004\020\245\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\005" +
    "\260\001\001\000\002\001\001\000\004\006\270\001\001" +
    "\000\002\001\001\000\004\007\264\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\007\273\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\007\027\015\300\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\007\303\001\001" +
    "\000\006\016\304\037\040\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\021\311\001\001\000\002\001\001" +
    "\000\002\001\001\000\022\022\051\023\054\024\052\025" +
    "\053\026\050\027\046\030\055\031\062\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\007" +
    "\027\013\316\014\022\015\024\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\016\321\037\040\001\001\000" +
    "\002\001\001\000\006\016\323\037\040\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\004" +
    "\327\005\255\001\001\000\004\005\260\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private java.util.List<String> erroresSintacticos = new java.util.ArrayList<>();
    public java.util.List<String> getErroresSintacticos() { return erroresSintacticos; }
    private boolean suppressBeginAfterMissingSemi = false;
    private boolean inVarGlobalsContext = false;

    private int ultimaLineaError = -1; // para evitar cascada
    //private int ultimaColumnaError = -1; 

    private String tok(Symbol s){
        if (s == null) return "<EOF>";
        // Detecta EOF por el símbolo, que es lo más confiable
        try {
            if (s.sym == sym.EOF) return "<EOF>";
        } catch (Exception ignore) {}

        // Si no hay valor o es vacío/espacios, trátalo como EOF
        if (s.value == null) return "<EOF>";
        String t = String.valueOf(s.value);
        if (t.trim().isEmpty()) return "<EOF>";
        return t;
    }


    /** registrar error (se puede modificar o extender los casos de errores...)*/
    private void addErr(int line, int col, String msg){
        // Silencia todos los errores adicionales en la misma línea
        if (line == ultimaLineaError) return;
        ultimaLineaError = line;

        String out = String.format("[Línea %d, Col %d] ERROR SINTACTICO: %s", line, col, msg);
        erroresSintacticos.add(out);
        System.out.println(out);
    }
    @Override
    public void syntax_error(java_cup.runtime.Symbol s) {
        // Evitar cascada: si estamos en VAR globales y el lookahead es BEGIN, no reportar
        if (s != null && s.sym == sym.BEGIN && inVarGlobalsContext) {
            return;
        }
        // Tipos en declaración VAR -> probablemente faltó ':'
        if (s != null &&
            (s.sym == sym.INT || s.sym == sym.REAL ||
            s.sym == sym.STRING || s.sym == sym.CHAR)) {
            addErr(s.left, s.right, "Declaracion de variable: se esperaba ':' antes del tipo");
            return;
        }
        // Evitar cascada: no reportar BEGIN inmediatamente después del ';' faltante
        if (s != null && s.sym == sym.BEGIN && suppressBeginAfterMissingSemi) {
            suppressBeginAfterMissingSemi = false;
            return;
        }

        int linea = (s != null ? s.left  : -1);
        int col   = (s != null ? s.right : -1);

        String mensaje;
        if (s == null || s.sym == sym.EOF) {
            mensaje = "Fin de archivo inesperado. ¿Falta el bloque principal BEGIN...END?";
        } else if (s.sym == sym.RPAREN) {
            mensaje = "Paréntesis de cierre ')' inesperado. ¿Falta un parámetro o expresión?";
        } else if (s.sym == sym.BEGIN) {
            mensaje = "'BEGIN' inesperado. ¿Falta cerrar una estructura anterior o falta ';'?";
        } else if (s.sym == sym.SEMI) {
            mensaje = "Punto y coma ';' inesperado. ¿Falta una sentencia o declaración?";
        } else if (s.sym == sym.END) {
            mensaje = "'END' inesperado. ¿Falta un 'BEGIN' correspondiente?";
        } else if (s.sym == sym.ELSE) {
            mensaje = "'ELSE' inesperado. ¿Falta un 'IF ... THEN' antes?";
        } else if (s.sym == sym.THEN) {
            mensaje = "'THEN' inesperado. ¿Falta la condición después de 'IF'?";
        } else if (s.sym == sym.DO) {
            mensaje = "'DO' inesperado. ¿Falta la condición después de 'WHILE' o expresión en 'FOR ... TO'?";
        } else if (s.sym == sym.COLON) {
            mensaje = "Dos puntos ':' inesperados. ¿En declaración de variables o tipo de retorno?";
        } else if (s.sym == sym.COMMA) {
            mensaje = "Coma ',' inesperada. ¿En lista de parámetros o declaración de variables?";
        } else if (s.sym == sym.ASSIGN) { // :=
            mensaje = "Asignación ':=' inesperada. ¿Falta el identificador a la izquierda?";
        } else if (s.sym == sym.LPAREN) {
            mensaje = "Paréntesis de apertura '(' inesperado. ¿En llamada a función o expresión?";
        } else {
            String tokenStr = tok(s);
            mensaje = "Token inesperado '" + tokenStr + "'";
        }

        addErr(linea, col, mensaje);

        if (s != null) {
            switch (s.sym) {
                case sym.SEMI:
                case sym.END:
                case sym.RPAREN:
                    ultimaLineaError = -1;
                    break;
            }
        }
    }

    @Override
    public void unrecovered_syntax_error(Symbol s) {
        int linea = (s.left > 0) ? s.left : -1;
        int col   = (s.right > 0) ? s.right : -1;

        String tokenStr = tok(s);
        
        addErr(linea, col,
            "Error sintáctico no recuperable cerca de '" + tokenStr + "'. " +
            "El parser no puede continuar desde este punto. " +
            "Revise la sintaxis de las estructuras anteriores.");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {

 // Código para el analisis semántico

  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= PROGRAM ID decls_globales_opt funcs_opt bloque_main 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= PROGRAM ID decls_globales_opt funcs_opt error 
            {
              Object RESULT =null;
		 
        addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left, 
               ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right, 
               "FALTA EL BLOQUE PRINCIPAL. Todo programa debe tener: BEGIN ... END"); 
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // programa ::= error 
            {
              Object RESULT =null;
		 
        addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left, 
               ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right, 
               "El archivo debe iniciar con 'Program <id>' seguido del bloque principal BEGIN...END"); 
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // NT$0 ::= 
            {
              Object RESULT =null;

            // Entramos al contexto de globales VAR
            inVarGlobalsContext = true;
         
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("NT$0",30, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // decls_globales_opt ::= VAR NT$0 lista_decl_var 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		
            // Salimos del contexto VAR al terminar la lista
            inVarGlobalsContext = false;
            RESULT = null;
         
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decls_globales_opt",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // decls_globales_opt ::= VAR error 
            {
              Object RESULT =null;
		
            // También activar y desactivar en la rama de error, para no “quedarnos pegados” en VAR
            inVarGlobalsContext = true;
            addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left,
                   ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right,
                   "Seccion VAR mal formada: usa 'id [, id]* : tipo ;'.");
            inVarGlobalsContext = false;
            RESULT = null;
         
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decls_globales_opt",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // decls_globales_opt ::= 
            {
              Object RESULT =null;
		
            RESULT = null;
         
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decls_globales_opt",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // lista_decl_var ::= lista_decl_var decl_var 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_decl_var",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_decl_var ::= decl_var 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_decl_var",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // decl_var ::= ID COLON tipo SEMI 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_var",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // decl_var ::= ID COMMA lista_ids COLON tipo SEMI 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_var",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // decl_var ::= ID error 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 addErr(idleft, idright, "Declaracion de variable: despues de '" + id + "' se esperaba ':' tipo ';' o ', id'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_var",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // decl_var ::= ID COLON tipo error 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		 
        addErr(idleft, idright, "Declaracion de variable: falta ';' despues de '" + id + " : tipo'."); 
        suppressBeginAfterMissingSemi = true;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_var",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // decl_var ::= ID COMMA lista_ids COLON tipo error 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-5)).value;
		 
        addErr(idleft, idright, "Declaracion de variable: falta ';' despues de 'id[, ids] : tipo'"); 
        suppressBeginAfterMissingSemi = true;
      
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decl_var",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista_ids ::= ID 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ids",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // lista_ids ::= lista_ids COMMA ID 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_ids",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipo ::= INT 
            {
              Object RESULT =null;
		 RESULT = "INT";    
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipo ::= REAL 
            {
              Object RESULT =null;
		 RESULT = "REAL";   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipo ::= CHAR 
            {
              Object RESULT =null;
		 RESULT = "CHAR";   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo ::= STRING 
            {
              Object RESULT =null;
		 RESULT = "STRING"; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // funcs_opt ::= lista_func 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcs_opt",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // funcs_opt ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcs_opt",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // lista_func ::= lista_func funcion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_func",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // lista_func ::= funcion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_func",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // funcion ::= FUNCTION ID LPAREN params_formales_opt RPAREN COLON tipo bloque_func 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // funcion ::= FUNCTION ID LPAREN error RPAREN COLON tipo bloque_func 
            {
              Object RESULT =null;
		int fnameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int fnameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String fname = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		 addErr(fnameleft, fnameright, 
                "FUNCIÓN '" + fname + "': Parámetros formales mal definidos. Formato esperado: 'tipo id, tipo id, ...'"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // funcion ::= PROCEDURE ID LPAREN params_formales_opt RPAREN bloque_func 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // funcion ::= PROCEDURE ID LPAREN error RPAREN bloque_func 
            {
              Object RESULT =null;
		int pfnameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int pfnameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String pfname = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		 addErr(pfnameleft, pfnameright, 
                "Parámetros mal formados en PROCEDURE '" + pfname + "'. Formato: 'tipo id' o vacío"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // params_formales_opt ::= lista_params_formales 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("params_formales_opt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // params_formales_opt ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("params_formales_opt",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // lista_params_formales ::= lista_params_formales COMMA param_formal 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_params_formales",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // lista_params_formales ::= param_formal 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_params_formales",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // param_formal ::= tipo ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_formal",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // param_formal ::= tipo error 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left, 
                ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right, 
                "Falta el identificador después del tipo en parámetro formal"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("param_formal",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // bloque_func ::= decls_locales_opt BEGIN lista_sentencias END 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_func",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // bloque_func ::= decls_locales_opt BEGIN error END 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right, "Cuerpo de funcion/procedimiento mal formado: verifica sentencias y ';'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_func",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // decls_locales_opt ::= VAR lista_decl_var 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decls_locales_opt",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // decls_locales_opt ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("decls_locales_opt",29, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // bloque_main ::= BEGIN lista_sentencias END 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_main",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // bloque_main ::= BEGIN error END 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right, "Bloque principal mal formado: verifica sentencias y ';' al final de cada una."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque_main",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // bloque ::= BEGIN lista_sentencias END 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // lista_sentencias ::= lista_sentencias sentencia 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // lista_sentencias ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // lista_sentencias ::= error SEMI 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right, "Se recupero de un error en una sentencia: probablemente falto ';' o la sentencia está mal formada."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_sentencias",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sentencia ::= asignacion SEMI 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sentencia ::= llamada_funcion_stmt SEMI 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // sentencia ::= read_stmt SEMI 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // sentencia ::= write_stmt SEMI 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // sentencia ::= if_stmt 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // sentencia ::= while_stmt 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // sentencia ::= for_stmt 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // asignacion ::= ID ASSIGN expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // asignacion ::= ID error expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		 addErr(idleft, idright, "Asignacion mal formada a '" + id  + "': falta ':='."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // llamada_funcion_stmt ::= ID LPAREN parametros_llamada_opt RPAREN 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("llamada_funcion_stmt",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // llamada_funcion_stmt ::= ID LPAREN error RPAREN 
            {
              Object RESULT =null;
		int fnameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int fnameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String fname = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		 addErr(fnameleft, fnameright, "Llamada a '" + fname  + "': argumentos mal formados dentro de '()'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("llamada_funcion_stmt",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // read_stmt ::= READ LPAREN RPAREN 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("read_stmt",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // read_stmt ::= READ LPAREN ID RPAREN 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("read_stmt",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // read_stmt ::= READ LPAREN error RPAREN 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right, "READ: se esperaba 0 o 1 identificador dentro de '()'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("read_stmt",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // write_stmt ::= WRITE LPAREN lista_expresiones RPAREN 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("write_stmt",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // write_stmt ::= WRITE LPAREN error RPAREN 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right, "WRITE: lista de expresiones mal formada dentro de '()'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("write_stmt",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // parametros_llamada_opt ::= lista_expresiones 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parametros_llamada_opt",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // parametros_llamada_opt ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("parametros_llamada_opt",24, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // lista_expresiones ::= lista_expresiones COMMA expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_expresiones",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // lista_expresiones ::= expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lista_expresiones",25, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // while_stmt ::= WHILE condicion DO bloque 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("while_stmt",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // while_stmt ::= WHILE error DO bloque 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right, "WHILE: condicion mal formada antes de 'DO'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("while_stmt",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // for_stmt ::= FOR ID ASSIGN expresion TO expresion DO bloque 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_stmt",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // for_stmt ::= FOR ID error expresion TO expresion DO bloque 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		 addErr(idleft, idright, "FOR: falta ':=' despues de '" +  id + "'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_stmt",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // for_stmt ::= FOR ID ASSIGN error TO expresion DO bloque 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right, "FOR: expresion inicial mal formada."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_stmt",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // for_stmt ::= FOR ID ASSIGN expresion TO error DO bloque 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right, "FOR: expresion final mal formada despues de 'TO'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("for_stmt",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // if_stmt ::= IF condicion THEN bloque 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // if_stmt ::= IF condicion THEN bloque ELSE bloque 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // if_stmt ::= IF error THEN bloque 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right, "IF: condicion mal formada antes de 'THEN'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // if_stmt ::= IF condicion THEN error 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right, "IF: bloque THEN mal formado. Recuerda usar 'BEGIN ... END'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // if_stmt ::= IF condicion THEN bloque ELSE error 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right, "IF: bloque ELSE mal formado. Recuerda usar 'BEGIN ... END'."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("if_stmt",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // condicion ::= expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",27, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // expresion ::= expresion PLUS expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // expresion ::= expresion MINUS expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // expresion ::= expresion TIMES expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // expresion ::= expresion SLASH expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // expresion ::= expresion DIV expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // expresion ::= expresion MOD expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // expresion ::= expresion INC 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // expresion ::= expresion DEC 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // expresion ::= INC expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // expresion ::= DEC expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // expresion ::= expresion EQ expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // expresion ::= expresion NEQ expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // expresion ::= expresion LT expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // expresion ::= expresion LE expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // expresion ::= expresion GT expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // expresion ::= expresion GE expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // expresion ::= expresion AND expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // expresion ::= expresion OR expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // expresion ::= NOT expresion 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // expresion ::= factor 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expresion",26, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // factor ::= ID 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // factor ::= INT_LIT 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // factor ::= REAL_LIT 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // factor ::= STRING_LIT 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // factor ::= CHAR_LIT 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // factor ::= ID LPAREN parametros_llamada_opt RPAREN 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // factor ::= LPAREN expresion RPAREN 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // factor ::= LPAREN error RPAREN 
            {
              Object RESULT =null;
		 addErr(((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right, "Expresion entre paréntesis mal formada."); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("factor",28, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
