
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INTERRUPT = 26;
  public static final int TIMES = 77;
  public static final int REAL = 56;
  public static final int GT = 74;
  public static final int PACKED = 34;
  public static final int TYPE = 45;
  public static final int READ = 54;
  public static final int CONST = 7;
  public static final int INT_LIT = 63;
  public static final int GE = 72;
  public static final int STRING_LIT = 60;
  public static final int SEMI = 65;
  public static final int UNTIL = 47;
  public static final int CONSTRUCTOR = 8;
  public static final int COMMA = 66;
  public static final int VIRTUAL = 50;
  public static final int RPAREN = 68;
  public static final int LT = 73;
  public static final int LPAREN = 67;
  public static final int SHR = 42;
  public static final int NOT = 30;
  public static final int LE = 71;
  public static final int NIL = 29;
  public static final int ARRAY = 4;
  public static final int OBJECT = 31;
  public static final int SHL = 41;
  public static final int ERROR = 83;
  public static final int DEC = 81;
  public static final int VAR = 49;
  public static final int INLINE = 24;
  public static final int THEN = 43;
  public static final int GOTO = 20;
  public static final int EXTERNAL = 15;
  public static final int RECORD = 38;
  public static final int EQ = 69;
  public static final int MOD = 28;
  public static final int SLASH = 78;
  public static final int WRITE = 53;
  public static final int PLUS = 75;
  public static final int UNIT = 46;
  public static final int WHILE = 51;
  public static final int IMPLEMENTATION = 22;
  public static final int ASSIGN = 64;
  public static final int INTERFACE = 25;
  public static final int CHAR = 57;
  public static final int DO = 11;
  public static final int FOR = 17;
  public static final int DIV = 10;
  public static final int DOWNTO = 12;
  public static final int RETURN = 59;
  public static final int ELSE = 13;
  public static final int PROCEDURE = 36;
  public static final int INT = 55;
  public static final int EOF = 0;
  public static final int REAL_LIT = 62;
  public static final int FUNCTION = 19;
  public static final int INC = 80;
  public static final int REPEAT = 39;
  public static final int LABEL = 27;
  public static final int MINUS = 76;
  public static final int DESTRUCTOR = 9;
  public static final int IN = 23;
  public static final int OR = 33;
  public static final int SET = 40;
  public static final int error = 1;
  public static final int IF = 21;
  public static final int ID = 82;
  public static final int OF = 32;
  public static final int END = 14;
  public static final int COLON = 79;
  public static final int FILE = 16;
  public static final int BEGIN = 5;
  public static final int CASE = 6;
  public static final int CHAR_LIT = 61;
  public static final int FORWARD = 18;
  public static final int STRING = 58;
  public static final int ABSOLUTE = 2;
  public static final int NEQ = 70;
  public static final int PROGRAM = 37;
  public static final int AND = 3;
  public static final int PRIVATE = 35;
  public static final int TO = 44;
  public static final int WITH = 52;
  public static final int USES = 48;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABSOLUTE",
  "AND",
  "ARRAY",
  "BEGIN",
  "CASE",
  "CONST",
  "CONSTRUCTOR",
  "DESTRUCTOR",
  "DIV",
  "DO",
  "DOWNTO",
  "ELSE",
  "END",
  "EXTERNAL",
  "FILE",
  "FOR",
  "FORWARD",
  "FUNCTION",
  "GOTO",
  "IF",
  "IMPLEMENTATION",
  "IN",
  "INLINE",
  "INTERFACE",
  "INTERRUPT",
  "LABEL",
  "MOD",
  "NIL",
  "NOT",
  "OBJECT",
  "OF",
  "OR",
  "PACKED",
  "PRIVATE",
  "PROCEDURE",
  "PROGRAM",
  "RECORD",
  "REPEAT",
  "SET",
  "SHL",
  "SHR",
  "THEN",
  "TO",
  "TYPE",
  "UNIT",
  "UNTIL",
  "USES",
  "VAR",
  "VIRTUAL",
  "WHILE",
  "WITH",
  "WRITE",
  "READ",
  "INT",
  "REAL",
  "CHAR",
  "STRING",
  "RETURN",
  "STRING_LIT",
  "CHAR_LIT",
  "REAL_LIT",
  "INT_LIT",
  "ASSIGN",
  "SEMI",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "EQ",
  "NEQ",
  "LE",
  "GE",
  "LT",
  "GT",
  "PLUS",
  "MINUS",
  "TIMES",
  "SLASH",
  "COLON",
  "INC",
  "DEC",
  "ID",
  "ERROR"
  };
}

